<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>13.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TieredCompilation>true</TieredCompilation>
		<Authors>David Liebeherr</Authors>
		<Company>rent-a-developer</Company>
		<Copyright>Copyright © rent-a-developer / David Liebeherr</Copyright>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageProjectUrl>https://github.com/rent-a-developer/AutoIndexCache</PackageProjectUrl>
		<PackageIcon>icon.png</PackageIcon>
		<RepositoryUrl>https://github.com/rent-a-developer/AutoIndexCache.git</RepositoryUrl>
		<RepositoryType>GIT</RepositoryType>
		<PackageTags>cache index automatic thread-safe</PackageTags>
		<Description>A high-performance, thread-safe cache for .NET applications that provides automatic indexing of cached data.</Description>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Version>1.3.0</Version>
		<PackageReleaseNotes>Performance optimizations.</PackageReleaseNotes>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
		<EnableNETAnalyzers>True</EnableNETAnalyzers>
		<AnalysisLevel>latest-all</AnalysisLevel>
		<TieredCompilation>true</TieredCompilation>
		<TieredPGO>true</TieredPGO>
		<RootNamespace>RentADeveloper.AutoIndexCache</RootNamespace>
		<AssemblyTitle>rent-a-developer AutoIndexCache</AssemblyTitle>
		<AssemblyName>RentADeveloper.AutoIndexCache</AssemblyName>
		<DocumentationFile>RentADeveloper.AutoIndexCache.xml</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md">
		  <Pack>True</Pack>
		  <PackagePath>\</PackagePath>
		</None>
		<None Include="icon.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	  <None Include="..\LICENSE.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="ErrorProne.NET.CoreAnalyzers" Version="0.1.2">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

</Project>
